# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_postid', models.IntegerField(unique=True)),
                ('m_title', models.CharField(max_length=255)),
                ('m_img', models.ImageField(upload_to='movie/%Y/%m/%d')),
                ('m_duration', models.TimeField()),
                ('m_paa_fu_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=16, unique=True)),
                ('u_passwd', models.CharField(max_length=128)),
                ('u_email', models.CharField(max_length=128, unique=True)),
                ('u_icon', models.ImageField(upload_to='icons/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='m_user',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
