# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180921_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='m_duration',
            field=models.IntegerField(),
        ),
    ]
