# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180921_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='more',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
