# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movie_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='more',
            new_name='m_more',
        ),
    ]
