# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180921_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='m_duration',
            field=models.CharField(max_length=10),
        ),
    ]
