# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180921_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_icon',
            field=models.ImageField(upload_to='%Y/%m/%d/icons'),
        ),
    ]
