# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180921_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='m_collected',
            field=models.IntegerField(default=0),
        ),
    ]
