# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32, unique=True)),
                ('u_passwd', models.CharField(max_length=255)),
                ('u_phone', models.CharField(max_length=16, unique=True)),
                ('u_icon', models.ImageField(upload_to='icons/%Y/%m/%d/')),
                ('u_is_delete', models.BooleanField(default=False)),
                ('u_is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
