# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-27 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forclass', '0002_auto_20180927_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_icon',
            field=models.ImageField(default='icons/default.jpg', upload_to='icons/%Y/%m/%d'),
        ),
    ]
