# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forclass', '0003_auto_20180927_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_ispay',
            field=models.BooleanField(default=False),
        ),
    ]
