# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-04 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_order_ordergoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_province', models.CharField(max_length=128)),
                ('a_city', models.CharField(max_length=256)),
                ('a_county', models.CharField(max_length=256)),
                ('a_detailed_address', models.CharField(max_length=256)),
                ('a_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.AXFUser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_province', models.CharField(max_length=128)),
                ('o_city', models.CharField(max_length=256)),
                ('o_county', models.CharField(max_length=256)),
                ('o_detailed_address', models.CharField(max_length=256)),
                ('o_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.Order')),
            ],
        ),
    ]
