# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_address_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='a_phone',
            field=models.CharField(default=123, max_length=16),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='o_phone',
            field=models.CharField(default=123, max_length=16),
        ),
    ]
