# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-06 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20181006_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='o_city',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='o_county',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='o_detailed_address',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='o_phone',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='o_province',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='o_username',
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='o_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.Address'),
        ),
    ]
