# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField(default=0)),
                ('c_parent_id', models.IntegerField(default=0)),
                ('c_region_name', models.CharField(max_length=16)),
                ('c_city_code', models.IntegerField(default=0)),
                ('c_pinyin', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='c_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_user.Letter'),
        ),
    ]
