# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=128)),
                ('g_price', models.FloatField(default=0)),
                ('g_des', models.TextField(default='无描述')),
                ('g_phone', models.IntegerField(default=12345678910)),
                ('g_addr', models.CharField(default='山西大学大东关校区', max_length=255)),
                ('g_img_one', models.ImageField(upload_to='goods/%Y/%m/%m/')),
                ('g_img_tow', models.ImageField(upload_to='goods/%Y/%m/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgood.Type'),
        ),
    ]
