# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='g_phone',
            field=models.CharField(default='12345678910', max_length=16),
        ),
    ]
