# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgood', '0002_auto_20180928_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='g_img_tow',
            new_name='g_img_two',
        ),
    ]
