# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgood', '0003_auto_20180928_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='g_collected',
            field=models.IntegerField(default=0),
        ),
    ]
