# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forclass', '0004_user_u_ispay'),
        ('forgood', '0004_good_g_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_select', models.BooleanField(default=True)),
                ('c_goods_num', models.IntegerField(default=1)),
                ('c_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgood.Good')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forclass.User')),
            ],
        ),
    ]
