"""empty message

Revision ID: 9f430ccb7afa
Revises: b614df364ab4
Create Date: 2018-10-17 21:39:47.882463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f430ccb7afa'
down_revision = 'b614df364ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_mainshow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('brandname', sa.String(length=64), nullable=True),
    sa.Column('img1', sa.String(length=255), nullable=True),
    sa.Column('childcid1', sa.Integer(), nullable=True),
    sa.Column('productid1', sa.Integer(), nullable=True),
    sa.Column('longname1', sa.String(length=128), nullable=True),
    sa.Column('price1', sa.Float(), nullable=True),
    sa.Column('marketprice1', sa.Float(), nullable=True),
    sa.Column('img2', sa.String(length=255), nullable=True),
    sa.Column('childcid2', sa.Integer(), nullable=True),
    sa.Column('productid2', sa.Integer(), nullable=True),
    sa.Column('longname2', sa.String(length=128), nullable=True),
    sa.Column('price2', sa.Float(), nullable=True),
    sa.Column('marketprice2', sa.Integer(), nullable=True),
    sa.Column('img3', sa.String(length=255), nullable=True),
    sa.Column('childcid3', sa.Integer(), nullable=True),
    sa.Column('productid3', sa.Integer(), nullable=True),
    sa.Column('longname3', sa.String(length=128), nullable=True),
    sa.Column('price3', sa.Float(), nullable=True),
    sa.Column('marketprice3', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_mustbuy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_shop')
    op.drop_table('axf_nav')
    op.drop_table('axf_mustbuy')
    op.drop_table('axf_mainshow')
    # ### end Alembic commands ###
