"""empty message

Revision ID: a649c70d0b3f
Revises: 6dff1fc4c2a1
Create Date: 2018-10-17 22:20:23.421641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a649c70d0b3f'
down_revision = '6dff1fc4c2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.Column('productimg', sa.String(length=255), nullable=True),
    sa.Column('productname', sa.String(length=128), nullable=True),
    sa.Column('productlongname', sa.String(length=255), nullable=True),
    sa.Column('isxf', sa.Boolean(), nullable=True),
    sa.Column('pmdesc', sa.Boolean(), nullable=True),
    sa.Column('specifics', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('marketprice', sa.Float(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('childcid', sa.Integer(), nullable=True),
    sa.Column('childcidname', sa.String(length=128), nullable=True),
    sa.Column('dealerid', sa.Integer(), nullable=True),
    sa.Column('storenums', sa.Integer(), nullable=True),
    sa.Column('productnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_goods')
    # ### end Alembic commands ###
